/* editabletests.js is part of Aloha Editor project http://aloha-editor.org
 *
 * Aloha Editor is a WYSIWYG HTML5 inline editing library and editor. 
 * Copyright (c) 2010-2012 Gentics Software GmbH, Vienna, Austria.
 * Contributors http://aloha-editor.org/contribution.php 
 * 
 * Aloha Editor is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * Aloha Editor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * 
 * As an additional permission to the GNU GPL version 2, you may distribute
 * non-source (e.g., minimized or compacted) forms of the Aloha-Editor
 * source code without the copy of the GNU GPL normally required,
 * provided you include this license notice and a URL through which
 * recipients can access the Corresponding Source.
 */

define(["testutils"],function(e){function t(t,n,r,i,s,o){e.setCursor(t,n,r),e.pressEnter(t,i),s&&e.pressEnter(t,i),Aloha.editables[0].obj.find("br.aloha-end-br").remove();var u=Aloha.editables[0].getContents(!0),a=Aloha.jQuery(o).contents();deepEqual(u.extractHTML(),a.extractHTML(),"Check Operation Result")}Aloha.bind("aloha-ready",function(){module("Plaintext Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-plaintext"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Enter at beginning",function(){t(this.edit,this.edit.contents().get(0),0,!1,!1,"#ref-plaintext-start-enter")}),test("Double Enter at beginning",function(){t(this.edit,this.edit.contents().get(0),0,!1,!0,"#ref-plaintext-start-dblenter")}),test("Enter in the middle",function(){t(this.edit,this.edit.contents().get(0),10,!1,!1,"#ref-plaintext-mid-enter")}),test("Double Enter in the middle",function(){t(this.edit,this.edit.contents().
get(0),10,!1,!0,"#ref-plaintext-mid-dblenter")}),test("Enter at end",function(){t(this.edit,this.edit.contents().get(0),18,!1,!1,"#ref-plaintext-end-enter")}),test("Double Enter at end",function(){t(this.edit,this.edit.contents().get(0),18,!1,!0,"#ref-plaintext-end-dblenter")}),module("Heading Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-heading"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Enter at start",function(){t(this.edit,this.edit.find("h1").contents().get(0),0,!1,!1,"#ref-heading-start-enter")}),test("Double Enter at start",function(){t(this.edit,this.edit.find("h1").contents().get(0),0,!1,!0,"#ref-heading-start-dblenter")}),test("Enter in middle",function(){t(this.edit,this.edit.find("h1").contents().get(0),3,!1,!1,"#ref-heading-mid-enter")}),test("Double Enter in middle",function(){t(this.edit,this.edit.find("h1").contents().get(0),3,!1,!0,"#ref-heading-mid-dblenter")}),test
("Enter in bold",function(){t(this.edit,this.edit.find("b").contents().get(0),2,!1,!1,"#ref-heading-bold-enter")}),test("Double Enter in bold",function(){t(this.edit,this.edit.find("b").contents().get(0),2,!1,!0,"#ref-heading-bold-dblenter")}),test("Enter at end",function(){t(this.edit,this.edit.find("h1").contents().last().get(0),8,!1,!1,"#ref-heading-end-enter")}),test("Double Enter at end",function(){t(this.edit,this.edit.find("h1").contents().last().get(0),8,!1,!0,"#ref-heading-end-dblenter")}),module("Heading Shift Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-heading"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Shift Enter at start",function(){t(this.edit,this.edit.find("h1").contents().get(0),0,!0,!1,"#ref-heading-start-shift-enter")}),test("Double Shift Enter at start",function(){t(this.edit,this.edit.find("h1").contents().get(0),0,!0,!0,"#ref-heading-start-shift-dblenter")}),
test("Shift Enter in middle",function(){t(this.edit,this.edit.find("h1").contents().get(0),3,!0,!1,"#ref-heading-mid-shift-enter")}),test("Double Shift Enter in middle",function(){t(this.edit,this.edit.find("h1").contents().get(0),3,!0,!0,"#ref-heading-mid-shift-dblenter")}),test("Shift Enter in bold",function(){t(this.edit,this.edit.find("b").contents().get(0),2,!0,!1,"#ref-heading-bold-shift-enter")}),test("Double Shift Enter in bold",function(){t(this.edit,this.edit.find("b").contents().get(0),2,!0,!0,"#ref-heading-bold-shift-dblenter")}),test("Shift Enter at end",function(){t(this.edit,this.edit.find("h1").contents().last().get(0),8,!0,!1,"#ref-heading-end-shift-enter")}),test("Double Shift Enter at end",function(){t(this.edit,this.edit.find("h1").contents().last().get(0),8,!0,!0,"#ref-heading-end-shift-dblenter")}),module("Paragraph Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-paragraph"),this.edit.html(this.ref.html()),this.edit.aloha
()},teardown:function(){this.edit.mahalo()}}),test("Enter at start",function(){t(this.edit,this.edit.find("p").contents().get(0),0,!1,!1,"#ref-paragraph-start-enter")}),test("Double Enter at start",function(){t(this.edit,this.edit.find("p").contents().get(0),0,!1,!0,"#ref-paragraph-start-dblenter")}),test("Enter in middle",function(){t(this.edit,this.edit.find("p").contents().get(2),3,!1,!1,"#ref-paragraph-mid-enter")}),test("Double Enter in middle",function(){t(this.edit,this.edit.find("p").contents().get(2),3,!1,!0,"#ref-paragraph-mid-dblenter")}),test("Enter at start of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),0,!1,!1,"#ref-paragraph-startitalic-enter")}),test("Double Enter at start of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),0,!1,!0,"#ref-paragraph-startitalic-dblenter")}),test("Enter in italic",function(){t(this.edit,this.edit.find("i").contents().get(0),3,!1,!1,"#ref-paragraph-miditalic-enter")}),test("Double Enter in italic"
,function(){t(this.edit,this.edit.find("i").contents().get(0),3,!1,!0,"#ref-paragraph-miditalic-dblenter")}),test("Enter at end of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),6,!1,!1,"#ref-paragraph-enditalic-enter")}),test("Double Enter at end of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),6,!1,!0,"#ref-paragraph-enditalic-dblenter")}),test("Enter at end",function(){t(this.edit,this.edit.find("p").contents().get(2),20,!1,!1,"#ref-paragraph-end-enter")}),test("Double Enter at end",function(){t(this.edit,this.edit.find("p").contents().get(2),20,!1,!0,"#ref-paragraph-end-dblenter")}),module("Paragraph Shift Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-paragraph"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Shift Enter at start",function(){t(this.edit,this.edit.find("p").contents().get(0),0,!0,!1,"#ref-paragraph-start-shift-enter")}),test
("Double Shift Enter at start",function(){t(this.edit,this.edit.find("p").contents().get(0),0,!0,!0,"#ref-paragraph-start-shift-dblenter")}),test("Shift Enter in middle",function(){t(this.edit,this.edit.find("p").contents().get(2),3,!0,!1,"#ref-paragraph-mid-shift-enter")}),test("Double Shift Enter in middle",function(){t(this.edit,this.edit.find("p").contents().get(2),3,!0,!0,"#ref-paragraph-mid-shift-dblenter")}),test("Shift Enter at start of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),0,!0,!1,"#ref-paragraph-startitalic-shift-enter")}),test("Double Shift Enter at start of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),0,!0,!0,"#ref-paragraph-startitalic-shift-dblenter")}),test("Shift Enter in italic",function(){t(this.edit,this.edit.find("i").contents().get(0),3,!0,!1,"#ref-paragraph-miditalic-shift-enter")}),test("Shift Enter at end of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),6,!0,!1,"#ref-paragraph-enditalic-shift-enter"
)}),test("Double Shift Enter at end of italic",function(){t(this.edit,this.edit.find("i").contents().get(0),6,!0,!0,"#ref-paragraph-enditalic-shift-dblenter")}),test("Double Shift Enter in italic",function(){t(this.edit,this.edit.find("i").contents().get(0),3,!0,!0,"#ref-paragraph-miditalic-shift-dblenter")}),test("Shift Enter at end",function(){t(this.edit,this.edit.find("p").contents().get(2),20,!0,!1,"#ref-paragraph-end-shift-enter")}),test("Double Shift Enter at end",function(){t(this.edit,this.edit.find("p").contents().get(2),20,!0,!0,"#ref-paragraph-end-shift-dblenter")}),module("List Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-list"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Enter at first start",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),0,!1,!1,"#ref-list-firststart-enter")}),test("Double Enter at first start",function(){t(this.edit,this.edit.find("li"
).eq(0).contents().get(0),0,!1,!0,"#ref-list-firststart-dblenter")}),test("Enter at first middle",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),2,!1,!1,"#ref-list-firstmid-enter")}),test("Double Enter at first middle",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),2,!1,!0,"#ref-list-firstmid-dblenter")}),test("Enter at first end",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),5,!1,!1,"#ref-list-firstend-enter")}),test("Double Enter at first end",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),5,!1,!0,"#ref-list-firstend-dblenter")}),test("Enter at second start",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),0,!1,!1,"#ref-list-secondstart-enter")}),test("Double Enter at second start",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),0,!1,!0,"#ref-list-secondstart-dblenter")}),test("Enter at second middle",function(){t(this.edit,this.edit.find("li").eq(1).contents().get
(0),3,!1,!1,"#ref-list-secondmid-enter")}),test("Double Enter at second middle",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),3,!1,!0,"#ref-list-secondmid-dblenter")}),test("Enter at second end",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),6,!1,!1,"#ref-list-secondend-enter")}),test("Double Enter at second end",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),6,!1,!0,"#ref-list-secondend-dblenter")}),test("Enter at last start",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),0,!1,!1,"#ref-list-laststart-enter")}),test("Double Enter at last start",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),0,!1,!0,"#ref-list-laststart-dblenter")}),test("Enter at last middle",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),2,!1,!1,"#ref-list-lastmid-enter")}),test("Double Enter at last middle",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),2,!1,!0,"#ref-list-lastmid-dblenter"
)}),test("Enter at last end",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),5,!1,!1,"#ref-list-lastend-enter")}),test("Double Enter at last end",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),5,!1,!0,"#ref-list-lastend-dblenter")}),module("Special List Enter Handling Tests",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-list-special1"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Enter after empty b",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(1),0,!1,!1,"#ref-list-enter-emptyb")}),module("List Shift Enter Handling",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-list"),this.edit.html(this.ref.html()),this.edit.aloha()},teardown:function(){this.edit.mahalo()}}),test("Shift Enter at first start",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),0,!0,!1,"#ref-list-firststart-shift-enter")}),test("Double Shift Enter at first start"
,function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),0,!0,!0,"#ref-list-firststart-shift-dblenter")}),test("Shift Enter at first middle",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),2,!0,!1,"#ref-list-firstmid-shift-enter")}),test("Double Shift Enter at first middle",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),2,!0,!0,"#ref-list-firstmid-shift-dblenter")}),test("Shift Enter at first end",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),5,!0,!1,"#ref-list-firstend-shift-enter")}),test("Double Shift Enter at first end",function(){t(this.edit,this.edit.find("li").eq(0).contents().get(0),5,!0,!0,"#ref-list-firstend-shift-dblenter")}),test("Shift Enter at second start",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),0,!0,!1,"#ref-list-secondstart-shift-enter")}),test("Double Shift Enter at second start",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),0,!0,!0,"#ref-list-secondstart-shift-dblenter"
)}),test("Shift Enter at second middle",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),3,!0,!1,"#ref-list-secondmid-shift-enter")}),test("Double Shift Enter at second middle",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),3,!0,!0,"#ref-list-secondmid-shift-dblenter")}),test("Shift Enter at second end",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),6,!0,!1,"#ref-list-secondend-shift-enter")}),test("Double Shift Enter at second end",function(){t(this.edit,this.edit.find("li").eq(1).contents().get(0),6,!0,!0,"#ref-list-secondend-shift-dblenter")}),test("Shift Enter at last start",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),0,!0,!1,"#ref-list-laststart-shift-enter")}),test("Double Shift Enter at last start",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),0,!0,!0,"#ref-list-laststart-shift-dblenter")}),test("Shift Enter at last middle",function(){t(this.edit,this.edit.find("li").eq(2).contents
().get(0),2,!0,!1,"#ref-list-lastmid-shift-enter")}),test("Double Shift Enter at last middle",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),2,!0,!0,"#ref-list-lastmid-shift-dblenter")}),test("Shift Enter at last end",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),5,!0,!1,"#ref-list-lastend-shift-enter")}),test("Double Shift Enter at last end",function(){t(this.edit,this.edit.find("li").eq(2).contents().get(0),5,!0,!0,"#ref-list-lastend-shift-dblenter")})})})