/* remove-markup.js is part of Aloha Editor project http://aloha-editor.org
 *
 * Aloha Editor is a WYSIWYG HTML5 inline editing library and editor. 
 * Copyright (c) 2010-2012 Gentics Software GmbH, Vienna, Austria.
 * Contributors http://aloha-editor.org/contribution.php 
 * 
 * Aloha Editor is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * Aloha Editor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * 
 * As an additional permission to the GNU GPL version 2, you may distribute
 * non-source (e.g., minimized or compacted) forms of the Aloha-Editor
 * source code without the copy of the GNU GPL normally required,
 * provided you include this license notice and a URL through which
 * recipients can access the Corresponding Source.
 */

define(["testutils"],function(e,t){function n(t,n,i,s,o,u,a,f){var l=e.generateRange(n,i,s,o);e.removeMarkup(t,l,u);var c=Aloha.editables[0].getContents(!0),h=r(f).contents();deepEqual(c.extractHTML(),h.extractHTML(),"Check Operation Result")}var r=window.jQuery,i=r("body");asyncTest("Aloha Startup Test",function(){Aloha.ready(function(){ok(!0,"Aloha Event was fired"),start()}),setTimeout(function(){ok(!1,"Aloha was not initialized within 60 seconds"),start()},6e4)}),Aloha.ready(function(){module("Remove Simple Markup",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-remove-simple"),this.edit.html(this.ref.html()),this.edit.aloha(),this.beforeBold=this.edit.contents().get(0),this.bold=this.edit.find("b").eq(0).contents().get(0),this.afterBold=this.edit.contents().get(2)},teardown:function(){this.edit.mahalo()}}),test("Before Occurrance",function(){n(this.edit,this.beforeBold,0,this.beforeBold,4,jQuery("<b></b>"),"#ref-remove-simple","#ref-remove-simple-before"
)}),test("Into Occurrance",function(){n(this.edit,this.beforeBold,0,this.bold,2,jQuery("<b></b>"),"#ref-remove-simple","#ref-remove-simple-into")}),test("Exact Occurrance",function(){n(this.edit,this.bold,0,this.bold,4,jQuery("<b></b>"),"#ref-remove-simple","#ref-remove-simple-exact")}),test("Across Occurrance",function(){n(this.edit,this.beforeBold,2,this.afterBold,3,jQuery("<b></b>"),"#ref-remove-simple","#ref-remove-simple-across")}),test("Out of Occurrance",function(){n(this.edit,this.bold,2,this.afterBold,3,jQuery("<b></b>"),"#ref-remove-simple","#ref-remove-simple-out")}),test("After Occurrance",function(){n(this.edit,this.afterBold,3,this.afterBold,5,jQuery("<b></b>"),"#ref-remove-simple","#ref-remove-simple-after")}),module("Remove Markup in Paragraph",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-remove-para"),this.edit.html(this.ref.html()),this.edit.aloha(),this.beforeBold=this.edit.find("p").eq(0).contents().get(0),this.bold=this.edit.find("b"
).eq(0).contents().get(0),this.afterBold=this.edit.find("p").eq(0).contents().get(2)},teardown:function(){this.edit.mahalo()}}),test("Before Occurrance",function(){n(this.edit,this.beforeBold,0,this.beforeBold,4,jQuery("<b></b>"),"#ref-remove-para","#ref-remove-para-before")}),test("Into Occurrance",function(){n(this.edit,this.beforeBold,0,this.bold,2,jQuery("<b></b>"),"#ref-remove-para","#ref-remove-para-into")}),test("Exact Occurrance",function(){n(this.edit,this.bold,0,this.bold,4,jQuery("<b></b>"),"#ref-remove-para","#ref-remove-para-exact")}),test("Across Occurrance",function(){n(this.edit,this.beforeBold,2,this.afterBold,3,jQuery("<b></b>"),"#ref-remove-para","#ref-remove-para-across")}),test("Out of Occurrance",function(){n(this.edit,this.bold,2,this.afterBold,3,jQuery("<b></b>"),"#ref-remove-para","#ref-remove-para-out")}),test("After Occurrance",function(){n(this.edit,this.afterBold,3,this.afterBold,5,jQuery("<b></b>"),"#ref-remove-para","#ref-remove-para-after")}),module("Remove Multiple Markup"
,{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-remove-multi"),this.edit.html(this.ref.html()),this.edit.aloha(),this.beforeBold=this.edit.contents().get(0),this.firstBold=this.edit.find("b").eq(0).contents().get(0),this.betweenBold=this.edit.contents().get(2),this.secondBold=this.edit.find("b").eq(1).contents().get(0),this.afterBold=this.edit.contents().get(4)},teardown:function(){this.edit.mahalo()}}),test("Across Occurrances",function(){n(this.edit,this.beforeBold,2,this.afterBold,3,jQuery("<b></b>"),"#ref-remove-multi","#ref-remove-multi-across")}),test("From Occurrance into another",function(){n(this.edit,this.firstBold,2,this.secondBold,2,jQuery("<b></b>"),"#ref-remove-multi","#ref-remove-multi-bold2bold")}),module("Remove Nested Markup",{setup:function(){this.edit=Aloha.jQuery("#edit"),this.ref=Aloha.jQuery("#ref-remove-nested"),this.edit.html(this.ref.html()),this.edit.aloha(),this.beforeBold=this.edit.contents().get(0),this.startBold=this.edit.find
("b").eq(0).contents().get(0),this.endBold=this.edit.find("b").eq(0).contents().get(2),this.italic=this.edit.find("i").eq(0).contents().get(0),this.afterBold=this.edit.contents().get(2)},teardown:function(){this.edit.mahalo()}}),test("Into inner Occurrance",function(){n(this.edit,this.beforeBold,5,this.italic,3,jQuery("<i></i>"),"#ref-remove-nested","#ref-remove-nested-inner-into")}),test("Exact inner Occurrance",function(){n(this.edit,this.italic,0,this.italic,6,jQuery("<i></i>"),"#ref-remove-nested","#ref-remove-nested-inner-exact")}),test("Across inner Occurrance",function(){n(this.edit,this.beforeBold,5,this.afterBold,4,jQuery("<i></i>"),"#ref-remove-nested","#ref-remove-nested-inner-across")}),test("Out of inner Occurrance",function(){n(this.edit,this.italic,3,this.afterBold,4,jQuery("<i></i>"),"#ref-remove-nested","#ref-remove-nested-inner-out")}),test("Into outer Occurrance",function(){n(this.edit,this.beforeBold,5,this.italic,3,jQuery("<b></b>"),"#ref-remove-nested","#ref-remove-nested-outer-into"
)}),test("Exactly outer Occurrance",function(){n(this.edit,this.startBold,0,this.endBold,5,jQuery("<b></b>"),"#ref-remove-nested","#ref-remove-nested-outer-exact")}),test("Across outer Occurrance",function(){n(this.edit,this.beforeBold,5,this.afterBold,4,jQuery("<b></b>"),"#ref-remove-nested","#ref-remove-nested-outer-across")}),test("Out of outer Occurrance",function(){n(this.edit,this.italic,3,this.afterBold,4,jQuery("<b></b>"),"#ref-remove-nested","#ref-remove-nested-outer-out")})})})