/* testutils.js is part of Aloha Editor project http://aloha-editor.org
 *
 * Aloha Editor is a WYSIWYG HTML5 inline editing library and editor. 
 * Copyright (c) 2010-2012 Gentics Software GmbH, Vienna, Austria.
 * Contributors http://aloha-editor.org/contribution.php 
 * 
 * Aloha Editor is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * Aloha Editor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * 
 * As an additional permission to the GNU GPL version 2, you may distribute
 * non-source (e.g., minimized or compacted) forms of the Aloha-Editor
 * source code without the copy of the GNU GPL normally required,
 * provided you include this license notice and a URL through which
 * recipients can access the Corresponding Source.
 */

window.TestUtils=window.TestUtils||{},define(["jquery","../../lib/aloha/ecma5shims"],function(e,t){return TestUtils=e.extend(!0,TestUtils,{createCollapsedRange:function(e,t){var n=new GENTICS.Utils.RangeObject({startContainer:e,startOffset:t,endContainer:e,endOffset:t});return n.correctRange(),n},setCursor:function(e,t,n){var r=this.createCollapsedRange(t,n);return e.focus(),r.select(),Aloha.Selection.updateSelection(),r},generateRange:function(e,t,n,r){var i=new Aloha.Selection.SelectionRange;return Aloha.Selection.rangeObject=i,i.startContainer=e,i.endContainer=n,i.startOffset=t,i.endOffset=r,i.update(),i},pressEnter:function(e,t){t?(e.simulate("keydown",{keyCode:13,shiftKey:!0}),e.simulate("keyup",{keyCode:13,shiftKey:!0})):(e.simulate("keydown",{keyCode:13}),e.simulate("keyup",{keyCode:13})),Aloha.Selection.updateSelection()},pressBackspace:function(e){e.simulate("keydown",{keyCode:8}),e.simulate("keyup",{keyCode:8})},applyMarkup:function(e,t,n,r){var i=!1;t.clearCaches(),t.updateMarkupEffectiveAtStart
();for(var s=0;s<t.markupEffectiveAtStart.length;s++){var o=t.markupEffectiveAtStart[s];Aloha.Selection.standardTextLevelSemanticsComparator(o,n)&&(i=!0)}i?GENTICS.Utils.Dom.removeMarkup(t,n,e):GENTICS.Utils.Dom.addMarkup(t,n,r),t.correctRange(),t.select(),t.clearCaches(),t.updateMarkupEffectiveAtStart()},removeMarkup:function(e,t,n){GENTICS.Utils.Dom.removeMarkup(t,n,e),t.correctRange(),t.select(),t.clearCaches(),t.updateMarkupEffectiveAtStart()},rangeFromMarker:function(e){var n,r,i=new Aloha.Selection.SelectionRange;return t(e.textNodes()).filter(function(){return this.nodeType==3&&this.nodeValue.indexOf("[")>=0}).each(function(){n=this.nodeValue,r=n.indexOf("["),this.nodeValue=n.substring(0,r)+n.substring(r+1),i.startContainer=this,i.startOffset=r}),t(e.textNodes()).filter(function(){return this.nodeType==3&&this.nodeValue.indexOf("]")>=0}).each(function(){n=this.nodeValue,r=n.indexOf("]"),this.nodeValue=n.substring(0,r)+n.substring(r+1),i.endContainer=this,i.endOffset=r}),i},markerFromSelection
:function(){var t=new Aloha.RangeObject,n=function(n,r,i){var s;n.nodeType==3?(s=n.nodeValue,t.endContainer.nodeValue=s.substring(0,r)+i+s.substring(r)):e(n).contents()[r].append("]")};t.initializeFromUserSelection(),n(t.endContainer,t.endOffset,"]"),n(t.startContainer,t.startOffset,"[")},addRange:function(n){function r(e){return e.hasChildNodes()?e.firstChild:i(e)}function i(e){while(e&&!e.nextSibling)e=e.parentNode;return e?e.nextSibling:null}function s(e){var t=0;while(e.previousSibling)t++,e=e.previousSibling;return t}var o=n.html(),u=/\{|\[|data-start/g,a=[],f;while(f=u.exec(o))a.push(f);if(a.length!=1)throw"Need exactly one start marker ([ or { or data-start), found "+a.length;var u=/\}|\]|data-end/g,a=[],f;while(f=u.exec(o))a.push(f);if(a.length!=1)throw"Need exactly one end marker (] or } or data-end), found "+a.length;var l=n[0],c,h,p,d;e(l).find("[data-start]")[0]&&(c=e(l).find("[data-start]")[0],h=c.getAttribute("data-start"),c.removeAttribute("data-start")),e(l).find("[data-end]"
)[0]&&(p=e(l).find("[data-end]")[0],d=p.getAttribute("data-end"),p.removeAttribute("data-end"));var v=l;for(;;){if(!v||v!=l&&!(t.compareDocumentPosition(v,l)&t.Node.DOCUMENT_POSITION_CONTAINS))break;if(v.nodeType!=t.Node.TEXT_NODE){v=r(v);continue}var m=v.data.replace(/[\]\}]/g,""),g=m.indexOf("[");m=v.data.replace(/[\[\{]/g,"");var y=m.indexOf("]");v.data=v.data.replace(/[\[\]]/g,""),g!=-1&&(c=v,h=g),y!=-1&&(p=v,d=y),m=v.data.replace(/\}/g,"");var b=m.indexOf("{");m=v.data.replace(/\{/g,"");var w=m.indexOf("}");b==0?(c=v.parentNode,h=s(v)):b!=-1&&(c=v.parentNode,h=s(v)+1),w==0?(p=v.parentNode,d=s(v)):w!=-1&&(p=v.parentNode,d=s(v)+1),v.data=v.data.replace(/[{}]/g,"");if(!v.data.length){if(v==c||v==p)throw"You put a square bracket where there was no text node . . .";var E=v;v=r(v),E.parentNode.removeChild(E)}else v=r(v)}var S=Aloha.createRange();return S.setStart(c,h),S.setEnd(p,d),S},addBrackets:function(e){var n;e.endContainer.nodeType==t.Node.TEXT_NODE||e.endContainer.nodeType==t.Node
.COMMENT_NODE?(e.collapsed?n="[]":n="]",e.endContainer.insertData(e.endOffset,n)):(e.collapsed?n="{}":n="}",e.endOffset!=e.endContainer.childNodes.length&&e.endContainer.childNodes[e.endOffset].nodeType==t.Node.TEXT_NODE?e.endContainer.childNodes[e.endOffset].insertData(0,n):e.endOffset!=0&&e.endContainer.childNodes[e.endOffset-1].nodeType==t.Node.TEXT_NODE?e.endContainer.childNodes[e.endOffset-1].appendData(n):e.endContainer.insertBefore(document.createTextNode(n),e.endContainer.childNodes.length==e.endOffset?null:e.endContainer.childNodes[e.endOffset]));if(e.collapsed)return;e.startContainer.nodeType==t.Node.TEXT_NODE||e.startContainer.nodeType==t.Node.COMMENT_NODE?e.startContainer.insertData(e.startOffset,"["):(n="{",e.startOffset!=e.startContainer.childNodes.length&&e.startContainer.childNodes[e.startOffset].nodeType==t.Node.TEXT_NODE?e.startContainer.childNodes[e.startOffset].insertData(0,n):e.startOffset!=0&&e.startContainer.childNodes[e.startOffset-1].nodeType==t.Node.TEXT_NODE?e
.startContainer.childNodes[e.startOffset-1].appendData(n):e.startContainer.insertBefore(document.createTextNode(n),e.startContainer.childNodes.length==e.startOffset?null:e.startContainer.childNodes[e.startOffset]))},permutations:function(e,t){var n,r,i,s,o,u=[];for(n in e)if(e.hasOwnProperty(n)){r=e[n];if(Aloha.jQuery.isArray(t)&&Aloha.jQuery.inArray(r,t)>=0)continue;i=Aloha.jQuery.extend([],t),i.push(r),u.push(i),s=this.permutations(e,i);for(o in s)s.hasOwnProperty(o)&&u.push(s[o])}return u}}),e.fn.extractHTML=function(t){t=typeof t=="undefined"?["class","id"]:t;var n=[];return typeof attr!="undefined"&&t.push(attr),e.each(this,function(){var r=e(this),i={};i.nodeName=r[0].nodeName.toLowerCase(),n.push(i);if(r[0].nodeType==3)i.text=r.text();else if(r[0].nodeType==1){e.each(t,function(e,t){i[t]=r.attr(t)});var s=r.contents();s.length&&(i.contents=s.extractHTML(t))}}),n},TestUtils})